"""
Deep Data Detective — HTML Report Generator.
Turns the progress.json into a beautiful standalone HTML report.
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Any

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Deep Data Detective — Report</title>
<style>
  :root {
    --bg: #0d1117;
    --surface: #161b22;
    --border: #30363d;
    --text: #c9d1d9;
    --muted: #8b949e;
    --accent: #58a6ff;
    --green: #3fb950;
    --orange: #d2991d;
    --red: #f85149;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
    padding: 40px 20px;
  }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { font-size: 2rem; margin-bottom: 4px; color: #fff; }
  h2 { font-size: 1.4rem; margin: 32px 0 12px; color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: 6px; }
  h3 { font-size: 1.1rem; margin: 20px 0 8px; color: #e6edf3; }
  .meta { color: var(--muted); font-size: 0.85rem; margin-bottom: 32px; }
  .card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 20px;
  }
  .card h3 { margin-top: 0; }
  .badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
  }
  .badge-ok { background: #1b3a1b; color: var(--green); }
  .badge-warn { background: #3a2e1b; color: var(--orange); }
  .badge-err { background: #3a1b1b; color: var(--red); }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 0.85rem;
  }
  th, td {
    text-align: left;
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
  }
  th { color: var(--muted); font-weight: 600; text-transform: uppercase; font-size: 0.75rem; }
  pre {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 16px;
    overflow-x: auto;
    font-size: 0.8rem;
    margin: 8px 0;
  }
  .narrative {
    background: #1a2332;
    border-left: 3px solid var(--accent);
    padding: 12px 16px;
    border-radius: 0 6px 6px 0;
    margin: 12px 0;
    font-style: italic;
    color: #bdd4f0;
  }
  .stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 12px;
    margin: 12px 0;
  }
  .stat-item {
    background: var(--bg);
    border-radius: 6px;
    padding: 12px;
    text-align: center;
  }
  .stat-value { font-size: 1.5rem; font-weight: 700; color: var(--accent); }
  .stat-label { font-size: 0.7rem; color: var(--muted); text-transform: uppercase; margin-top: 2px; }
  .exec-summary {
    background: linear-gradient(135deg, #1a2332 0%, #161b22 100%);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 28px;
    margin: 20px 0;
    font-size: 1.05rem;
    line-height: 1.8;
  }
  .exec-summary p { margin-bottom: 12px; }
  .exec-summary p:last-child { margin-bottom: 0; }
  footer { text-align: center; color: var(--muted); font-size: 0.75rem; margin-top: 48px; }
</style>
</head>
<body>
<div class="container">
{{ CONTENT }}
<footer>Generated by Deep Data Detective · {{ NOW }}</footer>
</div>
</body>
</html>"""


def _render_stats_grid(stats: dict) -> str:
    """Render the stats grid from overview phase."""
    items = [
        ("Rows", f"{stats.get('rows', 0):,}"),
        ("Columns", str(stats.get("cols", 0))),
        ("Memory", f"{stats.get('memory_mb', 0)} MB"),
        ("Duplicates", f"{stats.get('duplicates', 0)}"),
    ]
    grid = '<div class="stats-grid">'
    for label, value in items:
        grid += f'<div class="stat-item"><div class="stat-value">{value}</div><div class="stat-label">{label}</div></div>'
    grid += "</div>"
    return grid


def _render_dtypes(dtypes: dict) -> str:
    rows = "".join(
        f"<tr><td>{col}</td><td><span class='badge badge-ok'>{dtype}</span></td></tr>"
        for col, dtype in dtypes.items()
    )
    return f"<table><thead><tr><th>Column</th><th>Type</th></tr></thead><tbody>{rows}</tbody></table>"


def _render_missing_table(missing: dict) -> str:
    if not missing:
        return '<p style="color: var(--green);">✅ No missing values — dataset is complete!</p>'
    rows = "".join(
        f"<tr><td>{col}</td><td>{info['count']:,}</td><td>{info['pct']}%</td></tr>"
        for col, info in missing.items()
    )
    return f"<table><thead><tr><th>Column</th><th>Missing Count</th><th>%</th></tr></thead><tbody>{rows}</tbody></table>"


def _render_correlations(pairs: list) -> str:
    if not pairs:
        return "<p>No correlations computed.</p>"
    rows = "".join(
        f"<tr><td>{p['col1']}</td><td>{p['col2']}</td><td>{p['correlation']:.4f}</td></tr>"
        for p in pairs[:15]
    )
    return f"<table><thead><tr><th>Column A</th><th>Column B</th><th>Correlation</th></tr></thead><tbody>{rows}</tbody></table>"


def _render_distributions(dists: dict) -> str:
    if not dists:
        return "<p>No numeric columns to analyze.</p>"
    rows = []
    for col, d in list(dists.items())[:15]:
        rows.append(
            f"<tr><td>{col}</td><td>{d['mean']}</td><td>{d['std']}</td>"
            f"<td>{d['min']}</td><td>{d['p50']}</td><td>{d['max']}</td>"
            f"<td>{d['skew']}</td><td>{d['zeros_pct']}%</td></tr>"
        )
    header = "<tr><th>Column</th><th>Mean</th><th>Std</th><th>Min</th><th>Median</th><th>Max</th><th>Skew</th><th>Zeros%</th></tr>"
    return f"<table><thead>{header}</thead><tbody>{''.join(rows)}</tbody></table>"


def _render_outliers(iqr: dict, iso_count: int) -> str:
    if not iqr:
        return "<p>No outlier analysis.</p>"
    rows = "".join(
        f"<tr><td>{col}</td><td>{d['count']}</td><td>{d['pct']}%</td></tr>"
        for col, d in sorted(iqr.items(), key=lambda x: x[1]["count"], reverse=True)[:10]
    )
    return (
        f"<p>Isolation Forest flagged <strong>{iso_count}</strong> rows as anomalous (5% contamination).</p>"
        f"<table><thead><tr><th>Column</th><th>IQR Outliers</th><th>%</th></tr></thead><tbody>{rows}</tbody></table>"
    )


def _render_exec_summary(text: str) -> str:
    paragraphs = text.strip().split("\n\n")
    html = '<div class="exec-summary">'
    for p in paragraphs:
        html += f"<p>{p}</p>"
    html += "</div>"
    return html


def generate_report(progress_path: str = "output/progress.json", output_path: str = "output/report.html"):
    """Generate a beautiful HTML report from the analysis progress."""
    with open(progress_path) as f:
        progress = json.load(f)

    phases = progress.get("phases", {})
    sections = []

    # Header
    started = progress.get("started", "")[:19]
    finished = progress.get("finished", "")[:19]
    sections.append(f"<h1>🕵️ Deep Data Detective</h1>")
    sections.append(f'<p class="meta">Started: {started} · Finished: {finished}</p>')

    # ---- Phase: Overview ----
    ov = phases.get("overview", {})
    if ov and "error" not in ov:
        sections.append("<h2>📊 Dataset Overview</h2>")
        sections.append(_render_stats_grid(ov.get("stats", {})))
        sections.append(f'<div class="narrative">{ov.get("narrative", "")}</div>')
        sections.append("<h3>Column Types</h3>")
        sections.append(_render_dtypes(ov.get("stats", {}).get("dtypes", {})))

    # ---- Phase: Missingness ----
    ms = phases.get("missingness", {})
    if ms and "error" not in ms:
        sections.append("<h2>🕳️ Missing Values</h2>")
        sections.append(_render_missing_table(ms.get("missing_table", {})))
        sections.append(f'<div class="narrative">{ms.get("narrative", "")}</div>')

    # ---- Phase: Distributions ----
    ds = phases.get("distributions", {})
    if ds and "error" not in ds:
        sections.append("<h2>📈 Distributions</h2>")
        sections.append(_render_distributions(ds.get("distributions", {})))
        sections.append(f'<div class="narrative">{ds.get("narrative", "")}</div>')

    # ---- Phase: Correlations ----
    cr = phases.get("correlations", {})
    if cr and "error" not in cr:
        sections.append("<h2>🔗 Correlations</h2>")
        sections.append(_render_correlations(cr.get("top_correlations", [])))
        sections.append(f'<div class="narrative">{cr.get("narrative", "")}</div>')

    # ---- Phase: Outliers ----
    ol = phases.get("outliers", {})
    if ol and "error" not in ol:
        sections.append("<h2>🚨 Outliers</h2>")
        sections.append(_render_outliers(ol.get("iqr_outliers", {}), ol.get("iso_forest_flags", 0)))
        sections.append(f'<div class="narrative">{ol.get("narrative", "")}</div>')

    # ---- Phase: Clusters ----
    cl = phases.get("clusters", {})
    if cl and "error" not in cl:
        sections.append("<h2>🧩 Clusters</h2>")
        sizes = cl.get("cluster_sizes", {})
        if sizes:
            rows = "".join(
                f"<tr><td>Cluster {k}</td><td>{v:,} rows</td></tr>"
                for k, v in sizes.items()
            )
            sections.append(f"<table><thead><tr><th>Cluster</th><th>Size</th></tr></thead><tbody>{rows}</tbody></table>")
        sections.append(f'<div class="narrative">{cl.get("narrative", "")}</div>')

    # ---- Phase: Relationships ----
    rel = phases.get("relationships", {})
    if rel and "error" not in rel:
        sections.append("<h2>💡 Suggested Investigations</h2>")
        suggs = rel.get("suggested_investigations", [])
        if isinstance(suggs, list):
            items = "".join(f"<li>{s}</li>" for s in suggs)
            sections.append(f"<ul>{items}</ul>")

    # ---- Phase: Target-driven ----
    td = phases.get("target_driven", {})
    if td and "error" not in td and "No target" not in td.get("narrative", ""):
        sections.append("<h2>🎯 Target Analysis</h2>")
        sections.append(f'<div class="narrative">{td.get("narrative", "")}</div>')

    # ---- Phase: Story (Executive Summary) ----
    story = phases.get("story", {})
    if story and "error" not in story:
        sections.append("<h2>📝 Executive Summary</h2>")
        sections.append(_render_exec_summary(story.get("executive_summary", "")))

    html = HTML_TEMPLATE.replace("{{ CONTENT }}", "\n".join(sections)).replace(
        "{{ NOW }}", datetime.now().strftime("%Y-%m-%d %H:%M")
    )

    with open(output_path, "w") as f:
        f.write(html)

    print(f"📄 Report saved to {output_path}")
    return output_path


if __name__ == "__main__":
    generate_report()
